[package]
name = "punkt"
version = "0.0.2"
authors = ["Ferris Tseng <ferristseng@fastmail.fm>"]

[dependencies]
log = "0.1.9"
phf = "0.4.9"
phf_mac = "0.4.9"
xxhash = "0.0.8"
rust-freqdist = "0.0.4"
rustc-serialize = "0.2.7"
