[package]
name = "punkt"
version = "0.0.3"
authors = ["Ferris Tseng <ferristseng@fastmail.fm>"]
license = "MIT"
repository = "https://github.com/ferristseng/rust-punkt"

[dependencies]
log = "0.1.10"
phf = "0.5.0"
phf_mac = "0.5.0"
xxhash = "0.0.8"
rust-freqdist = "0.0.4"
rustc-serialize = "0.2.9"
